# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/requirements" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "main" # The branch into which the updates should be merged
    allow:
      - dependency-name: "todoist-api-python"
      - dependency-name: "keyring"
    ignore:
      - dependency-name: "docs/doxygen-awesome-css"
      - dependency-name: "doxygen-awesome-css"
      - dependency-name: "https://github.com/jothepro/doxygen-awesome-css.git"


