coverage:
  status:
    project: # add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default: # status check name
        target: auto
        threshold: 1% # the leniency in hitting the target
        paths:
          - "src"
    patch:
      default:
        target: 100%
        paths:
          - "src"